version: '3.8'

services:
  app:
    container_name: e-wp-thailand-extract-and-translate
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    build:
      context: .
      dockerfile: Dockerfile

    build:
      context: .
      dockerfile: Dockerfile
